version: '3'
services:
  db:
    image: postgres:14.2-alpine
    container_name: jedis-om30-postgres-14.2
    volumes:
      - postgres_data:/var/lib/postgresql/data
    command: "postgres -c 'max_connections=500'"
    environment:
      POSTGRES_DB: jedis-om30-dev
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
  jedis-om30-project:
    build: .
    command: "bundle exec rails s -p 3000 -b '0.0.0.0'"
    environment:
      DB_HOST: db
      DB_NAME: jedis-om30-dev
      DB_USERNAME: admin
      DB_PASSWORD: password
    volumes:
      - .:/app:cached
    ports:
      - "3000:3000"
    depends_on:
      - db
volumes:
  postgres_data: {}
networks:
  default:
    name: jedis-om30-project-default